application: where-do-you-go
version: 3-0
runtime: python
api_version: 1

handlers:

- url: /delete_data/all
  script: scripts/delete_data.py
  login: admin

- url: /delete_data/user
  script: scripts/delete_data.py
  login: required


- url: /generate_static_map/all
  script: scripts/update_user_maps.py
  login: admin

- url: /generate_static_map/.*
  script: scripts/update_user_maps.py
  login: required


- url: /fetch_foursquare_data
  script: scripts/fetch_foursquare_data.py
  login: admin

- url: /clear_authtokens
  script: scripts/clear_authtokens.py
  login: admin

- url: /view_venues
  script: handlers.py
  login: admin

- url: /static
  static_dir: static

- url: .*
  script: handlers.py