application: where-do-you-go
version: 2-3
runtime: python
api_version: 1

handlers:
- url: /fetch_all_recent_checkins
  script: scripts/fetch_all_recent_checkins.py
  login: admin

- url: /delete_all_data
  script: scripts/delete_all_data.py
  login: admin

- url: /clear_authtokens
  script: scripts/clear_authtokens.py
  login: admin

- url: .*
  script: handlers.py